### ISSUE TITLE
Detect and remedy the situation when the database needs to be updated

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/SlicerIDCBrowser#13]
As experienced by @ulrikew 

<img width="1208" alt="image" src="https://github.com/ImagingDataCommons/SlicerIDCBrowser/assets/313942/3b3bc7df-c97b-414d-aa77-d866e537733f">

<img width="857" alt="image" src="https://github.com/ImagingDataCommons/SlicerIDCBrowser/assets/313942/9c84bef1-d2d3-44aa-b3fc-25b1bfe52271">

**Comment by fedorov** [comment]
@pieper do you know how to detect this programmatically?

**Comment by pieper** [comment]
@fedorov Didn't we already fix this before you went to MICCAI?  I recall I gave you like three API calls that should work for this.

If that didn't work though, are you able to reproduce so we can debug?

**Comment by fedorov** [comment]
@pieper I think it is this line in the commit above that hopefully fixed the issue: https://github.com/ImagingDataCommons/SlicerIDCBrowser/commit/6a04ce68cecf28ab9bd019f8a1f7d5adfb341dbe#diff-bd4005884968d1d9d5119c23314e06369783363963750fd5d27ea26653d3f78bR105.
