### ISSUE TITLE
Error in getting response from IDC server

### ISSUE THREAD

**Issue by deepakri201** [ImagingDataCommons/SlicerIDCBrowser#17]
Hi @fedorov, 

I installed the latest version of the extension for Slicer 5.4.0 on Windows. When I open the extension, the following error occurs:

![image](https://github.com/ImagingDataCommons/SlicerIDCBrowser/assets/59979551/82ffb729-0b20-470f-8bca-9aab050d1e2b)

Checking the logs: 

![image](https://github.com/ImagingDataCommons/SlicerIDCBrowser/assets/59979551/fb0ddf3e-9869-4971-86b0-5d9f2ece6a85)

Thanks!

Deepa

**Comment by bcli4d** [comment]
The Slicer interface is currently against the dev API which is, by definition, not stable.
At this moment, I've deployed an update to the API itself but it depends on an update to the webapp which has not yet been deployed.
Sorry for the inconvenience.

**Comment by fedorov** [comment]
> The Slicer interface is currently against the dev API which is, by definition, not stable.

Right, but I thought it is the only one that is usable. The "prod" API does not meet the requirements of the Slicer module, if I remember correctly.

In any case, I think we have a plan.

**Comment by bcli4d** [comment]
The v2 API is up again. 

Work-in-progress documentation is [here](https://app.gitbook.com/o/-MCNUE8xpdPUJwWRz6xu/s/-MCTG4fXybYgGMalZnmf-2668963341/~/changes/324/api/getting-started).

I revised the following functions in Andrey's slicer/API interface to be compatible with the revisions to the API, an to demonstrate required revisions. 
- get_image
- get_patient
- get_patient_study
- get_series

The revised version of the Slicer/API code is [here](https://drive.google.com/drive/u/0/search?q=slicer.py). 

Four filters/fields:
- PatientAge
- PatientSex
- PatientSize
- PatientWeight

are not yet available through the webapp, so are not available through the API. I'll try to get that taken care of.

The point of the dev API is to be able to gain experience and improve it before going to test or production. Let me know if you have questions or suggestions.

**Comment by fedorov** [comment]
Resolved by switching to using local index.
