### ISSUE TITLE
Don't install python packages during startup

### ISSUE THREAD

**Issue by pieper** [ImagingDataCommons/SlicerIDCBrowser#25]
Issue: after installing the extension Slicer takes a long time to start up which could make users think the program has hung.

In this image you can see that many python packages are being installed when the module is being detected, but this would not be visible to most users who launch from a icon.

![image](https://github.com/ImagingDataCommons/SlicerIDCBrowser/assets/126077/e6bdae80-c223-41b9-a59b-79e20d0aee71)

Suggested fix:

This code should be moved so that it doesn't run during module discovery:

https://github.com/ImagingDataCommons/SlicerIDCBrowser/blob/dc7b361cd2735fb6dc9c5ded9fb266ffd4a0dca7/IDCBrowser/IDCBrowser.py#L36-L38

Instead, it would be good to follow the practice like in the TotalSegmentator extension, where installation of large packages is done specifically when the user requests it and GUI feedback is provided.

**Comment by fedorov** [comment]
Agreed, good point!

**Comment by fedorov** [comment]
@pieper please reopen if you have any concerns after checking out the updated version!
